services:
  tunnel-client:
    image: darkver8/cosmo-nps-client:latest
    container_name: tunnel-client
    restart: unless-stopped
    network_mode: host
    entrypoint: ["/usr/local/bin/tunnel-client"]
    environment:
      CONTROL_URL: ${CONTROL_URL}
      TUNNEL_USER: ${TUNNEL_USER}
      TUNNEL_PASSWORD: ${TUNNEL_PASSWORD}
    logging:
      driver: local
      options:
        max-size: "20m"
        max-file: "3"
