services:
  tunnel-stack:
    image: darkver8/cosmo-nps:latest
    container_name: tunnel-stack
    restart: unless-stopped
    network_mode: host
    environment:
      PUBLIC_ADDR: ${PUBLIC_ADDR}
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
    volumes:
      - ./data:/app/data
    logging:
      driver: local
      options:
        max-size: "50m"
        max-file: "7"
