appname = nps
runmode = pro

http_proxy_ip=0.0.0.0
http_proxy_port=9080
https_proxy_port=9443
https_just_proxy=true

bridge_type=tcp
bridge_port=18024
bridge_ip=0.0.0.0

tls_enable=true
tls_bridge_port=18025

public_vkey=
flow_store_interval=1
log_level=6
log_path=/data/nps.log

web_host=
web_username=admin
web_password=change-this-nps-password
web_port=0
web_ip=127.0.0.1
web_base_url=
web_open_ssl=false

auth_key=change-this-auth-key
auth_crypt_key=change16bytekey

allow_ports=10000-20000
allow_user_login=true
allow_user_register=false
allow_user_change_username=true
allow_flow_limit=true
allow_rate_limit=true
allow_tunnel_num_limit=true
allow_local_proxy=false
allow_connection_num_limit=true
allow_multi_ip=true
system_info_display=true
http_add_origin_header=true

http_cache=false
http_cache_length=100
disconnect_timeout=60
open_captcha=false
